// lib/player/session.dart
import 'dart:math';

/// One playback context. Lives in memory only.
class PlaybackSession {
  PlaybackSession({
    required this.id,
    required this.tmdbId,
    required this.mediaType,
    required this.pluginShortName,
    required this.upstreamMasterUrl,
    required this.upstreamHeaders,
    required this.isDrm,
    required this.drmKeys,
    required this.createdAt,
    required this.lastSeenAt,
  });

  factory PlaybackSession.create({
    required int tmdbId,
    required String mediaType,
    required String pluginShortName,
    required String upstreamMasterUrl,
    required Map<String, String> upstreamHeaders,
    bool isDrm = false,
    Map<String, dynamic>? drmKeys,
  }) {
    final now = DateTime.now();
    return PlaybackSession(
      id: _newId(),
      tmdbId: tmdbId,
      mediaType: mediaType,
      pluginShortName: pluginShortName,
      upstreamMasterUrl: upstreamMasterUrl,
      upstreamHeaders: Map.unmodifiable(upstreamHeaders),
      isDrm: isDrm,
      drmKeys: drmKeys,
      createdAt: now,
      lastSeenAt: now,
    );
  }

  final String id;
  final int tmdbId;
  final String mediaType;
  final String pluginShortName;
  final String upstreamMasterUrl;
  final Map<String, String> upstreamHeaders;
  final bool isDrm;
  final Map<String, dynamic>? drmKeys;
  final DateTime createdAt;
  DateTime lastSeenAt;

  /// Per-rendition upstream URL — populated lazily by the proxy when it
  /// first sees a request for `/variant/{sid}/{rendition}.m3u8` (the
  /// rendition label was generated by Rewriter from the master playlist).
  final Map<String, String> renditionUpstream = {};
}

String _newId() {
  // 16 hex chars — collision-resistant enough for in-process registry.
  final r = Random.secure();
  return List.generate(16, (_) => r.nextInt(16).toRadixString(16)).join();
}

class PlaybackSessionRegistry {
  PlaybackSessionRegistry({required Duration ttl}) : _ttl = ttl;

  final Duration _ttl;
  final Map<String, PlaybackSession> _sessions = {};

  void put(PlaybackSession s) {
    _sessions[s.id] = s;
  }

  PlaybackSession? get(String id, {bool touch = false}) {
    final s = _sessions[id];
    if (s == null) return null;
    if (DateTime.now().difference(s.lastSeenAt) > _ttl) {
      _sessions.remove(id);
      return null;
    }
    if (touch) s.lastSeenAt = DateTime.now();
    return s;
  }

  void remove(String id) {
    _sessions.remove(id);
  }

  int purgeExpired() {
    final now = DateTime.now();
    final toDrop = _sessions.entries
        .where((e) => now.difference(e.value.lastSeenAt) > _ttl)
        .map((e) => e.key)
        .toList();
    for (final id in toDrop) {
      _sessions.remove(id);
    }
    return toDrop.length;
  }
}
